Repository matrix-org/dendrite, pull requests merged in 2020-01, with the labels that each got.

#840 Amend syncapi SQL queries to return missing columns
  syncapi/storage/current_room_state_table.go
  syncapi/storage/output_room_events_table.go
Labels: bug

#842 Fall back to postgres when database connection string parsing fails
  common/keydb/keydb.go
  federationsender/storage/storage.go
  mediaapi/storage/storage.go
  publicroomsapi/storage/storage.go
  roomserver/storage/storage.go
  syncapi/storage/storage.go
Labels: bug

#845 Federation fixes
  clientapi/routing/joinroom.go
  go.mod
  go.sum
  roomserver/query/query.go
  syncapi/routing/state.go
  syncapi/storage/postgres/account_data_table.go
  syncapi/storage/postgres/current_room_state_table.go
  syncapi/storage/postgres/output_room_events_table.go
  syncapi/storage/postgres/syncserver.go
  syncapi/storage/storage.go
  syncapi/sync/requestpool.go
Labels: bug, component:federation

#847 CS API: Support for /messages, fixes for /sync
  cmd/dendrite-monolith-server/main.go
  cmd/dendrite-sync-api-server/main.go
  roomserver/api/query.go
  roomserver/query/query.go
  syncapi/consumers/clientapi.go
  syncapi/consumers/roomserver.go
  syncapi/consumers/typingserver.go
  syncapi/routing/messages.go
  syncapi/routing/routing.go
  syncapi/storage/postgres/account_data_table.go
  syncapi/storage/postgres/backward_extremities_table.go
  syncapi/storage/postgres/current_room_state_table.go
  syncapi/storage/postgres/invites_table.go
  syncapi/storage/postgres/output_room_events_table.go
  syncapi/storage/postgres/output_room_events_topology_table.go
  syncapi/storage/postgres/syncserver.go
  syncapi/storage/storage.go
  syncapi/sync/notifier.go
  syncapi/sync/notifier_test.go
  syncapi/sync/request.go
  syncapi/sync/requestpool.go
  syncapi/sync/userstream.go
  syncapi/syncapi.go
  syncapi/types/types.go
  syncapi/types/types_test.go
  sytest-blacklist
  sytest-whitelist
Labels: component:clientapi, component:syncserver

#850 Some fixes for #847
  go.mod
  go.sum
  syncapi/routing/messages.go
  syncapi/storage/postgres/backward_extremities_table.go
  syncapi/storage/postgres/output_room_events_table.go
Labels: bug, component:syncserver

#851 Wire up publicroomsapi for roomserver events
  cmd/dendrite-monolith-server/main.go
  cmd/dendrite-public-rooms-api-server/main.go
  publicroomsapi/publicroomsapi.go
  publicroomsapi/storage/postgres/storage.go
  syncapi/routing/messages.go
Labels: component:publicrooms

#854 More sync fixes
  syncapi/storage/postgres/output_room_events_topology_table.go
  syncapi/storage/postgres/syncserver.go
Labels: bug

#862 Add empty push rules into account data on account creation
  clientapi/auth/storage/accounts/storage.go
Labels: component:clientapi

#860 Handle kind=guest query parameter on /register
  clientapi/routing/register.go
  go.mod
  sytest-whitelist
Labels: component:clientapi
