Repository matrix-org/dendrite, pull requests merged in 2020-11, with the labels that each got.

#1572 Implement forgetting about rooms
  clientapi/routing/membership.go
  clientapi/routing/routing.go
  federationapi/routing/send_test.go
  roomserver/api/api.go
  roomserver/api/api_trace.go
  roomserver/api/perform.go
  roomserver/api/query.go
  roomserver/internal/api.go
  roomserver/internal/perform/perform_forget.go
  roomserver/internal/perform/perform_invite.go
  roomserver/internal/query/query.go
  roomserver/inthttp/client.go
  roomserver/inthttp/server.go
  roomserver/storage/interface.go
  roomserver/storage/postgres/deltas/20201028212440_add_forgotten_column.go
  roomserver/storage/postgres/membership_table.go
  roomserver/storage/postgres/storage.go
  roomserver/storage/shared/membership_updater.go
  roomserver/storage/shared/storage.go
  roomserver/storage/sqlite3/deltas/20201028212440_add_forgotten_column.go
  roomserver/storage/sqlite3/membership_table.go
  roomserver/storage/sqlite3/storage.go
  roomserver/storage/tables/interface.go
  syncapi/routing/messages.go
  sytest-whitelist
Labels: component:clientapi, component:roomserver

#1578 Fix username regex to allow = character
  clientapi/routing/register.go
Labels: bug, spec-compliance

#1587 Protect txnReq.newEvents with mutex
  federationapi/routing/send.go
Labels: bug

#1589 MSC2836: Threading - part one
  cmd/dendrite-monolith-server/main.go
  federationsender/api/api.go
  federationsender/internal/perform.go
  federationsender/internal/query.go
  internal/config/config.go
  internal/config/config_mscs.go
  internal/hooks/hooks.go
  internal/mscs/msc2836/msc2836.go
  internal/mscs/msc2836/msc2836_test.go
  internal/mscs/msc2836/storage.go
  internal/mscs/mscs.go
  roomserver/api/perform.go
  roomserver/internal/input/input.go
  roomserver/internal/perform/perform_join.go
Labels: feature-req

#1593 Update last seen on sync requests
  dendrite-config.yaml
  internal/config/config_syncapi.go
  internal/mscs/msc2836/msc2836_test.go
  syncapi/sync/requestpool.go
  syncapi/syncapi.go
  userapi/api/api.go
  userapi/internal/api.go
  userapi/inthttp/client.go
  userapi/inthttp/server.go
  userapi/storage/devices/interface.go
  userapi/storage/devices/postgres/devices_table.go
  userapi/storage/devices/postgres/storage.go
  userapi/storage/devices/sqlite3/devices_table.go
  userapi/storage/devices/sqlite3/storage.go
Labels: component:syncserver, component:userapi
