Repository matrix-org/dendrite, pull requests merged in 2021-07, with the labels that each got.

#1897 Federation API workers for /send to reduce memory usage
  federationapi/routing/send.go
Labels: component:federation

#1899 Federation API fixes
  federationapi/routing/send.go
Labels: component:federation

#1901 Add dendrite-upgrade-test
  cmd/dendrite-upgrade-tests/main.go
  cmd/dendrite-upgrade-tests/tar.go
  cmd/dendrite-upgrade-tests/tests.go
  go.mod
  go.sum
Labels: tests

#1903 dendrite-upgrade-test: support --from HEAD-N, cleanup on startup
  cmd/dendrite-upgrade-tests/main.go
Labels: tests

#1904 db migration: handle create events with no state blocks from v0.1.0
  roomserver/storage/postgres/deltas/2021041615092700_state_blocks_refactor.go
Labels: bug

#1906 Only log filename and not entire path
  internal/log.go
Labels: maintenance

#1908 bugfix: order the state blocks so recreating state snapshots works correctly
  roomserver/storage/postgres/state_block_table.go
  roomserver/storage/sqlite3/state_block_table.go
Labels: bug

#1909 Add more optimised code path for checking if we're in a room
  federationapi/routing/send.go
  federationapi/routing/send_test.go
  roomserver/api/query.go
  roomserver/internal/api.go
  roomserver/internal/query/query.go
  roomserver/storage/interface.go
  roomserver/storage/postgres/membership_table.go
  roomserver/storage/shared/storage.go
  roomserver/storage/sqlite3/membership_table.go
  roomserver/storage/tables/interface.go
Labels: component:federation, component:roomserver, optimisation

#1911 Implement /_synapse/admin/v1/register
  build/gobind-pinecone/monolith.go
  build/gobind-yggdrasil/monolith.go
  clientapi/clientapi.go
  clientapi/routing/register.go
  clientapi/routing/register_secret.go
  clientapi/routing/register_secret_test.go
  clientapi/routing/routing.go
  cmd/dendrite-demo-libp2p/main.go
  cmd/dendrite-demo-pinecone/main.go
  cmd/dendrite-demo-yggdrasil/main.go
  cmd/dendrite-monolith-server/main.go
  cmd/dendrite-polylith-multi/personalities/clientapi.go
  cmd/dendritejs-pinecone/main.go
  cmd/dendritejs/main.go
  go.mod
  go.sum
  setup/base.go
  setup/monolith.go
Labels: feature-req

#1912 Replace some helpers.IsServerCurrentlyInRoom calls with query API
  roomserver/internal/api.go
  roomserver/internal/helpers/helpers.go
  roomserver/internal/perform/perform_join.go
  roomserver/internal/query/query.go
Labels: component:roomserver

#1914 update whitelist
  sytest-whitelist
Labels: tests

#1918 bugfix: retire invites even when we cannot talk to the remote server to make/send_leave
  roomserver/internal/perform/perform_leave.go
  syncapi/streams/stream_invite.go
  sytest-whitelist
Labels: bug

#1920 sytests: fix failing PL tests by updating GMSL
  go.mod
  go.sum
  sytest-whitelist
Labels: bug

#1921 Update dendrite-demo-yggdrasil to Yggdrasil 0.4
  build/gobind-yggdrasil/monolith.go
  cmd/dendrite-demo-yggdrasil/convert/25519.go
  cmd/dendrite-demo-yggdrasil/convert/25519_test.go
  cmd/dendrite-demo-yggdrasil/main.go
  cmd/dendrite-demo-yggdrasil/yggconn/client.go
  cmd/dendrite-demo-yggdrasil/yggconn/node.go
  cmd/dendrite-demo-yggdrasil/yggconn/session.go
  cmd/dendrite-demo-yggdrasil/yggconn/stream.go
  go.mod
  go.sum
Labels: demo:yggdrasil

#1923 fedsender: add cache tables for notary keys
  federationapi/routing/keys.go
  federationsender/api/api.go
  federationsender/internal/api.go
  federationsender/internal/query.go
  federationsender/inthttp/client.go
  federationsender/inthttp/server.go
  federationsender/storage/interface.go
  federationsender/storage/postgres/notary_server_keys_json_table.go
  federationsender/storage/postgres/notary_server_keys_metadata_table.go
  federationsender/storage/postgres/storage.go
  federationsender/storage/shared/storage.go
  federationsender/storage/sqlite3/notary_server_keys_json_table.go
  federationsender/storage/sqlite3/notary_server_keys_metadata_table.go
  federationsender/storage/sqlite3/storage.go
  federationsender/storage/tables/interface.go
  sytest-whitelist
Labels: feature-req

#1931 Fix failing Complement tests
  federationapi/routing/join.go
  federationapi/routing/leave.go
Labels: tests

#1900 Only include go-sqlite3 on the relevant binaries
  appservice/storage/sqlite3/storage.go
  cmd/dendrite-demo-libp2p/main.go
  cmd/dendrite-demo-pinecone/main.go
  cmd/dendrite-demo-yggdrasil/main.go
  cmd/dendrite-monolith-server/main.go
  cmd/dendrite-polylith-multi/main.go
  federationsender/storage/sqlite3/storage.go
  go.mod
  go.sum
  internal/sqlutil/sql.go
  internal/sqlutil/trace.go
  mediaapi/storage/sqlite3/storage.go
  roomserver/storage/sqlite3/storage.go
  signingkeyserver/storage/sqlite3/keydb.go
  syncapi/storage/sqlite3/syncserver.go
  userapi/storage/devices/sqlite3/storage.go
Labels: maintenance

#1933 Optimise QueryServerJoinedToRoom
  roomserver/api/query.go
  roomserver/internal/query/query.go
  roomserver/storage/interface.go
  roomserver/storage/postgres/membership_table.go
  roomserver/storage/shared/storage.go
  roomserver/storage/sqlite3/membership_table.go
  roomserver/storage/tables/interface.go
Labels: optimisation

#1940 Not finding the snapshot is not fatal
  roomserver/storage/postgres/deltas/2021041615092700_state_blocks_refactor.go
Labels: bug

#1943 Key backups (1/2) : Add E2E session backup metadata tables
  clientapi/routing/key_backup.go
  clientapi/routing/routing.go
  setup/mscs/msc2836/msc2836_test.go
  setup/mscs/msc2946/msc2946_test.go
  sytest-whitelist
  userapi/api/api.go
  userapi/internal/api.go
  userapi/inthttp/client.go
  userapi/storage/accounts/interface.go
  userapi/storage/accounts/postgres/key_backup_version_table.go
  userapi/storage/accounts/postgres/storage.go
  userapi/storage/accounts/sqlite3/key_backup_version_table.go
  userapi/storage/accounts/sqlite3/storage.go
Labels: are-we-synapse-yet, component:clientapi, component:userapi, feature-req

#1944 Use db writer on sqlite account table
  userapi/storage/accounts/sqlite3/storage.go
Labels: bug, component:userapi

#1945 Key Backups (2/3) : Add E2E backup key tables
  clientapi/routing/key_backup.go
  clientapi/routing/routing.go
  sytest-whitelist
  userapi/api/api.go
  userapi/internal/api.go
  userapi/storage/accounts/interface.go
  userapi/storage/accounts/postgres/key_backup_table.go
  userapi/storage/accounts/postgres/key_backup_version_table.go
  userapi/storage/accounts/postgres/storage.go
  userapi/storage/accounts/sqlite3/key_backup_table.go
  userapi/storage/accounts/sqlite3/key_backup_version_table.go
  userapi/storage/accounts/sqlite3/storage.go
Labels: are-we-synapse-yet, component:clientapi, component:userapi, feature-req

#1946 Key Backups (3/3) : Implement querying keys and various bugfixes
  clientapi/routing/key_backup.go
  clientapi/routing/routing.go
  sytest-whitelist
  userapi/api/api.go
  userapi/internal/api.go
  userapi/storage/accounts/interface.go
  userapi/storage/accounts/postgres/key_backup_table.go
  userapi/storage/accounts/postgres/key_backup_version_table.go
  userapi/storage/accounts/postgres/storage.go
  userapi/storage/accounts/sqlite3/key_backup_table.go
  userapi/storage/accounts/sqlite3/key_backup_version_table.go
  userapi/storage/accounts/sqlite3/storage.go
Labels: are-we-synapse-yet, component:clientapi, component:userapi, feature-req
