Repository matrix-org/dendrite, pull requests merged in 2022-12, with the labels that each got.

#2898 Add tests for the AS internal API
  appservice/appservice_test.go
Labels: maintenance, component:appservices, tests

#2904 Update contributing guidelines
  docs/CONTRIBUTING.md
Labels: T-Task

#2906 Fix issue with multiple/duplicate log entries during tests
  internal/log.go
  internal/log_unix.go
Labels: T-Task

#2907 Add UserAPI util tests
  test/testrig/base.go
  userapi/util/notify_test.go
  userapi/util/phonehomestats.go
  userapi/util/phonehomestats_test.go
Labels: T-Task

#2857 Cleanup stale device lists for users we don't share a room with anymore
  build/dendritejs-pinecone/main.go
  build/gobind-pinecone/monolith.go
  build/gobind-yggdrasil/monolith.go
  cmd/dendrite-demo-pinecone/main.go
  cmd/dendrite-demo-yggdrasil/main.go
  cmd/dendrite-monolith-server/main.go
  cmd/dendrite-polylith-multi/personalities/keyserver.go
  keyserver/internal/device_list_update.go
  keyserver/internal/device_list_update_test.go
  keyserver/keyserver.go
  keyserver/keyserver_test.go
  keyserver/storage/interface.go
  keyserver/storage/postgres/stale_device_lists.go
  keyserver/storage/shared/storage.go
  keyserver/storage/sqlite3/stale_device_lists.go
  keyserver/storage/tables/interface.go
  keyserver/storage/tables/stale_device_lists_test.go
  roomserver/api/api.go
  roomserver/api/api_trace.go
  roomserver/api/query.go
  roomserver/internal/query/query.go
  roomserver/inthttp/client.go
  roomserver/inthttp/server.go
  roomserver/roomserver_test.go
  roomserver/storage/interface.go
  roomserver/storage/postgres/membership_table.go
  roomserver/storage/shared/storage.go
  roomserver/storage/shared/storage_test.go
  roomserver/storage/sqlite3/membership_table.go
  roomserver/storage/tables/interface.go
  roomserver/storage/tables/membership_table_test.go
Labels: C-Roomserver, C-Keyserver, T-Task

#2920 Add federation peeking table tests
  federationapi/queue/queue_test.go
  federationapi/storage/interface.go
  federationapi/storage/postgres/inbound_peeks_table.go
  federationapi/storage/postgres/outbound_peeks_table.go
  federationapi/storage/postgres/queue_edus_table.go
  federationapi/storage/postgres/queue_pdus_table.go
  federationapi/storage/shared/storage_edus.go
  federationapi/storage/shared/storage_pdus.go
  federationapi/storage/sqlite3/inbound_peeks_table.go
  federationapi/storage/sqlite3/outbound_peeks_table.go
  federationapi/storage/sqlite3/queue_edus_table.go
  federationapi/storage/sqlite3/queue_pdus_table.go
  federationapi/storage/storage_test.go
  federationapi/storage/tables/inbound_peeks_table_test.go
  federationapi/storage/tables/interface.go
  federationapi/storage/tables/outbound_peeks_table_test.go
Labels: C-Federation, T-Task

#2921 Fix reset password endpoint
  clientapi/admin_test.go
  clientapi/clientapi.go
  clientapi/routing/admin.go
  clientapi/routing/password.go
  clientapi/routing/register.go
  clientapi/routing/routing.go
  docs/administration/4_adminapi.md
  internal/httputil/httpapi.go
  internal/validate.go
  test/user.go
Labels: C-Client-API, T-Defect

#2872 Handle guest access [1/2?]
  clientapi/clientapi.go
  clientapi/routing/joinroom.go
  clientapi/routing/joinroom_test.go
  roomserver/api/perform.go
  roomserver/internal/api.go
  roomserver/internal/input/input.go
  roomserver/internal/input/input_events.go
  roomserver/internal/perform/perform_join.go
  roomserver/roomserver_test.go
  setup/config/config_global.go
  setup/config/config_test.go
  sytest-blacklist
  sytest-whitelist
  test/room.go
  userapi/api/api.go
  userapi/api/api_trace.go
  userapi/internal/api.go
  userapi/inthttp/client.go
  userapi/inthttp/server.go
  userapi/userapi_test.go
Labels: T-Enhancement

#2918 Pushrule tweaks, make `pattern` non-optional on `EventMatchCondition`
  internal/pushrules/condition.go
  internal/pushrules/default_content.go
  internal/pushrules/default_override.go
  internal/pushrules/default_pushrules_test.go
  internal/pushrules/default_underride.go
  internal/pushrules/evaluate.go
  internal/pushrules/evaluate_test.go
  internal/pushrules/pushrules.go
  internal/pushrules/util.go
  internal/pushrules/validate.go
  internal/pushrules/validate_test.go
  userapi/consumers/roomserver_test.go
Labels: C-Sync-API, C-User-API, T-Defect, F-Push

#2916 Add clientapi tests
  .github/workflows/dendrite.yml
  clientapi/routing/admin.go
  clientapi/routing/auth_fallback.go
  clientapi/routing/auth_fallback_test.go
  clientapi/routing/login.go
  clientapi/routing/password.go
  clientapi/routing/register.go
  clientapi/routing/register_test.go
  clientapi/routing/routing.go
  cmd/create-account/main.go
  internal/httputil/httpapi.go
  internal/validate.go
  internal/validate_test.go
  setup/config/config.go
  setup/config/config_clientapi.go
Labels: tests, T-Task, T-Defect

#2901 Add possibility to run complement with coverage enabled
  Dockerfile
  build/scripts/Complement.Dockerfile
  build/scripts/ComplementLocal.Dockerfile
  build/scripts/ComplementPostgres.Dockerfile
  build/scripts/complement-cmd.sh
Labels: T-Task
