Repository matrix-org/dendrite, pull requests merged in 2023-01, with the labels that each got.

#2926 Fix backfilling
  go.mod
  go.sum
  roomserver/internal/perform/perform_backfill.go
Labels: C-Federation, T-Defect, S-Major

#2905 Add simplified helm chart
  .github/workflows/gh-pages.yml
  .github/workflows/helm.yml
  .github/workflows/k8s.yml
  helm/cr.yaml
  helm/ct.yaml
  helm/dendrite/.helm-docs/about.gotmpl
  helm/dendrite/.helm-docs/appservices.gotmpl
  helm/dendrite/.helm-docs/database.gotmpl
  helm/dendrite/.helm-docs/state.gotmpl
  helm/dendrite/Chart.yaml
  helm/dendrite/README.md
  helm/dendrite/README.md.gotmpl
  helm/dendrite/ci/ct-ingress-values.yaml
  helm/dendrite/ci/ct-postgres-sharedsecret-values.yaml
  helm/dendrite/templates/_helpers.tpl
  helm/dendrite/templates/_overrides.yaml
  helm/dendrite/templates/deployment.yaml
  helm/dendrite/templates/ingress.yaml
  helm/dendrite/templates/jobs.yaml
  helm/dendrite/templates/pvc.yaml
  helm/dendrite/templates/secrets.yaml
  helm/dendrite/templates/service.yaml
  helm/dendrite/templates/tests/test-version.yaml
  helm/dendrite/values.yaml
  setup/config/config.go
Labels: T-Enhancement

#2922 Fix `/login` issue causing wrong device list updates
  clientapi/auth/login_test.go
  clientapi/auth/password.go
  clientapi/routing/login_test.go
Labels: C-Client-API, T-Defect, S-Major

#2930 Fix room summary returning wrong heroes
  syncapi/storage/interface.go
  syncapi/storage/postgres/current_room_state_table.go
  syncapi/storage/postgres/memberships_table.go
  syncapi/storage/shared/storage_sync.go
  syncapi/storage/sqlite3/current_room_state_table.go
  syncapi/storage/sqlite3/memberships_table.go
  syncapi/storage/storage_test.go
  syncapi/storage/tables/interface.go
  syncapi/storage/tables/memberships_test.go
  syncapi/streams/stream_pdu.go
Labels: C-Sync-API, T-Defect

#2939 Switch the default config option values for `recaptcha_sitekey_class` and `recaptcha_form_field`
  setup/config/config_clientapi.go
Labels: T-Defect, S-Minor

#2940 Omit state field from `/messages` response if empty
  syncapi/routing/messages.go
Labels: C-Sync-API, spec-compliance

#2927 `/sync` performance optimizations
  federationapi/consumers/roomserver.go
  syncapi/routing/memberships.go
  syncapi/routing/messages.go
  syncapi/storage/interface.go
  syncapi/storage/postgres/output_room_events_topology_table.go
  syncapi/storage/shared/storage_sync.go
  syncapi/storage/sqlite3/output_room_events_topology_table.go
  syncapi/storage/storage_test.go
  syncapi/storage/tables/interface.go
  syncapi/streams/stream_pdu.go
  syncapi/syncapi_test.go
Labels: C-Sync-API, T-Enhancement

#2662 Add `/_dendrite/admin/purgeRoom/{roomID}` (PostgreSQL only)
  clientapi/admin_test.go
  clientapi/routing/admin.go
  clientapi/routing/routing.go
  federationapi/consumers/roomserver.go
  federationapi/storage/interface.go
  federationapi/storage/shared/storage.go
  internal/sqlutil/sql.go
  internal/sqlutil/sqlutil_test.go
  roomserver/api/api.go
  roomserver/api/api_trace.go
  roomserver/api/output.go
  roomserver/api/perform.go
  roomserver/internal/perform/perform_admin.go
  roomserver/inthttp/client.go
  roomserver/inthttp/server.go
  roomserver/roomserver_test.go
  roomserver/storage/interface.go
  roomserver/storage/postgres/purge_statements.go
  roomserver/storage/postgres/rooms_table.go
  roomserver/storage/postgres/storage.go
  roomserver/storage/shared/storage.go
  roomserver/storage/sqlite3/purge_statements.go
  roomserver/storage/sqlite3/rooms_table.go
  roomserver/storage/sqlite3/state_block_table.go
  roomserver/storage/sqlite3/state_snapshot_table.go
  roomserver/storage/sqlite3/storage.go
  roomserver/storage/tables/interface.go
  syncapi/consumers/roomserver.go
  syncapi/storage/interface.go
  syncapi/storage/postgres/backwards_extremities_table.go
  syncapi/storage/postgres/invites_table.go
  syncapi/storage/postgres/memberships_table.go
  syncapi/storage/postgres/notification_data_table.go
  syncapi/storage/postgres/output_room_events_table.go
  syncapi/storage/postgres/output_room_events_topology_table.go
  syncapi/storage/postgres/peeks_table.go
  syncapi/storage/postgres/receipt_table.go
  syncapi/storage/shared/storage_consumer.go
  syncapi/storage/shared/storage_sync.go
  syncapi/storage/sqlite3/backwards_extremities_table.go
  syncapi/storage/sqlite3/invites_table.go
  syncapi/storage/sqlite3/memberships_table.go
  syncapi/storage/sqlite3/notification_data_table.go
  syncapi/storage/sqlite3/output_room_events_table.go
  syncapi/storage/sqlite3/output_room_events_topology_table.go
  syncapi/storage/sqlite3/peeks_table.go
  syncapi/storage/sqlite3/receipt_table.go
  syncapi/storage/tables/interface.go
Labels: C-Roomserver, C-Sync-API, C-Federation, T-Enhancement

#2948 Make tests more reliable
  federationapi/federationapi.go
  federationapi/federationapi_test.go
  federationapi/routing/routing.go
  setup/base/base.go
  test/testrig/base.go
Labels: T-Task

#2943 AWSY missing federation tests
  are-we-synapse-yet.list
  go.mod
  go.sum
  roomserver/internal/input/input_events.go
  sytest-blacklist
  sytest-whitelist
Labels: C-Roomserver, T-Task

#2933 Change Default Room version to 10
  roomserver/version/version.go
Labels: T-Enhancement

#2950 Use `t.TempDir` for SQLite databases, so tests don't rip out each others databases
  cmd/generate-config/main.go
  internal/log.go
  internal/log_unix.go
  setup/jetstream/helpers.go
  sytest-blacklist
  sytest-whitelist
  test/db.go
  test/testrig/base.go
Labels: T-Task

#2885 Added Landing Page
  internal/httputil/paths.go
  setup/base/base.go
  setup/base/base_test.go
  setup/base/static/index.gotmpl
Labels: T-Enhancement
