Repository matrix-org/dendrite, pull requests merged in 2023-04, with the labels that each got.

#3034 Add tests for CSAPI membership changes
  clientapi/clientapi_test.go
  clientapi/routing/membership.go
  clientapi/routing/sendtyping.go
Labels: spec-compliance, tests, T-Task

#3038 Add tests for `/turnServer`, `/capabilities` and `/3pid/`
  clientapi/auth/authtypes/threepid.go
  clientapi/clientapi_test.go
  clientapi/routing/capabilities.go
  clientapi/routing/routing.go
  clientapi/routing/threepid.go
  clientapi/threepid/threepid.go
  roomserver/api/api.go
  roomserver/api/query.go
  roomserver/internal/query/query.go
Labels: tests, T-Task, T-Defect

#3045 Move GMSL client types to Dendrite
  appservice/appservice_test.go
  appservice/consumers/roomserver.go
  clientapi/routing/state.go
  roomserver/api/query.go
  roomserver/internal/query/query.go
  setup/mscs/msc2836/msc2836.go
  setup/mscs/msc2836/msc2836_test.go
  syncapi/internal/keychange.go
  syncapi/internal/keychange_test.go
  syncapi/routing/context.go
  syncapi/routing/context_test.go
  syncapi/routing/filter.go
  syncapi/routing/getevent.go
  syncapi/routing/memberships.go
  syncapi/routing/messages.go
  syncapi/routing/relations.go
  syncapi/routing/search.go
  syncapi/routing/search_test.go
  syncapi/storage/interface.go
  syncapi/storage/postgres/account_data_table.go
  syncapi/storage/postgres/current_room_state_table.go
  syncapi/storage/postgres/filter_table.go
  syncapi/storage/postgres/filtering.go
  syncapi/storage/postgres/output_room_events_table.go
  syncapi/storage/postgres/presence_table.go
  syncapi/storage/shared/storage_consumer.go
  syncapi/storage/shared/storage_sync.go
  syncapi/storage/shared/storage_sync_test.go
  syncapi/storage/sqlite3/account_data_table.go
  syncapi/storage/sqlite3/current_room_state_table.go
  syncapi/storage/sqlite3/filter_table.go
  syncapi/storage/sqlite3/output_room_events_table.go
  syncapi/storage/sqlite3/presence_table.go
  syncapi/storage/storage_test.go
  syncapi/storage/tables/current_room_state_test.go
  syncapi/storage/tables/interface.go
  syncapi/storage/tables/output_room_events_test.go
  syncapi/storage/tables/presence_table_test.go
  syncapi/streams/stream_accountdata.go
  syncapi/streams/stream_invite.go
  syncapi/streams/stream_pdu.go
  syncapi/streams/stream_presence.go
  syncapi/streams/stream_receipt.go
  syncapi/streams/stream_typing.go
  syncapi/sync/request.go
  syncapi/sync/requestpool_test.go
  syncapi/syncapi_test.go
  syncapi/synctypes/clientevent.go
  syncapi/synctypes/clientevent_test.go
  syncapi/synctypes/filter.go
  syncapi/synctypes/filter_test.go
  syncapi/types/provider.go
  syncapi/types/types.go
  syncapi/types/types_test.go
  userapi/api/api.go
  userapi/consumers/roomserver.go
  userapi/storage/storage_test.go
  userapi/util/notify_test.go
Labels: T-Task

#3048 ci: don't use go get, use go install
  .github/workflows/dendrite.yml
Labels: tests, T-Task

#3052 Update GMSL: use static Check functions
  federationapi/internal/perform.go
  go.mod
  go.sum
  roomserver/api/wrapper.go
  roomserver/internal/input/input_missing.go
  setup/mscs/msc2836/msc2836.go
Labels: T-Task

#3044 Add pushrules tests
  clientapi/clientapi_test.go
  clientapi/routing/pushrules.go
  internal/pushrules/validate.go
  userapi/api/api.go
  userapi/internal/user_api.go
Labels: C-Client-API, tests, T-Task

#3043 Add sync API db tests
  syncapi/storage/postgres/output_room_events_table.go
  syncapi/storage/shared/storage_consumer_test.go
  syncapi/storage/sqlite3/output_room_events_table.go
  syncapi/storage/tables/interface.go
  syncapi/storage/tables/output_room_events_test.go
Labels: tests, T-Defect

#3062 Implement new RoomVersionImpl API
  federationapi/federationapi_test.go
  federationapi/internal/perform.go
  federationapi/queue/queue_test.go
  federationapi/routing/invite.go
  federationapi/routing/join.go
  federationapi/routing/leave.go
  federationapi/routing/threepid.go
  go.mod
  go.sum
  internal/eventutil/events.go
  internal/pushrules/evaluate_test.go
  internal/transactionrequest.go
  internal/transactionrequest_test.go
  roomserver/internal/helpers/helpers.go
  roomserver/internal/input/input_missing.go
  roomserver/internal/input/input_test.go
  roomserver/internal/query/query.go
  roomserver/internal/query/query_test.go
  roomserver/state/state.go
  roomserver/storage/postgres/state_snapshot_table.go
  roomserver/storage/shared/storage.go
  roomserver/version/version.go
  syncapi/synctypes/clientevent_test.go
  syncapi/types/types_test.go
  userapi/consumers/roomserver_test.go
Labels: T-Task

#3064 Use IRoomVersion
  clientapi/clientapi_test.go
  clientapi/routing/capabilities.go
  cmd/dendrite-upgrade-tests/main.go
  federationapi/routing/invite.go
  go.mod
  go.sum
  roomserver/version/version.go
Labels: T-Task

#3067 Add some roomserver UTs
  clientapi/routing/createroom.go
  clientapi/routing/joinroom_test.go
  clientapi/routing/profile.go
  clientapi/routing/sendevent.go
  clientapi/routing/server_notices.go
  federationapi/routing/join.go
  federationapi/routing/leave.go
  federationapi/routing/peek.go
  federationapi/routing/threepid.go
  internal/transactionrequest.go
  internal/transactionrequest_test.go
  roomserver/api/api.go
  roomserver/auth/auth.go
  roomserver/auth/auth_test.go
  roomserver/internal/input/input_events.go
  roomserver/internal/perform/perform_upgrade.go
  roomserver/internal/query/query.go
  roomserver/roomserver_test.go
  roomserver/storage/shared/storage.go
  setup/mscs/msc2836/msc2836.go
Labels: C-Roomserver, T-Task, T-Defect

#3070 Use PDU interface
  clientapi/routing/sendevent.go
  cmd/resolve-state/main.go
  federationapi/internal/perform.go
  federationapi/routing/backfill.go
  federationapi/routing/join.go
  federationapi/routing/leave.go
  go.mod
  go.sum
  internal/transactionrequest.go
  roomserver/api/wrapper.go
  roomserver/internal/helpers/auth.go
  roomserver/internal/input/input_events.go
  roomserver/internal/input/input_missing.go
  roomserver/internal/perform/perform_admin.go
  roomserver/internal/perform/perform_backfill.go
  roomserver/internal/perform/perform_inbound_peek.go
  roomserver/internal/perform/perform_upgrade.go
  roomserver/internal/query/query.go
  roomserver/state/state.go
  roomserver/storage/interface.go
  roomserver/storage/shared/storage.go
  setup/mscs/msc2836/msc2836.go
  syncapi/streams/stream_pdu.go
Labels: T-Task

#3072 Use PDU in more places
  appservice/consumers/roomserver.go
  clientapi/routing/state.go
  go.mod
  go.sum
  internal/pushrules/evaluate.go
  internal/pushrules/evaluate_test.go
  setup/mscs/msc2836/msc2836.go
  syncapi/routing/context.go
  syncapi/routing/getevent.go
  syncapi/routing/memberships.go
  syncapi/routing/messages.go
  syncapi/routing/search.go
  syncapi/streams/stream_pdu.go
  syncapi/synctypes/clientevent.go
  userapi/consumers/roomserver.go
  userapi/util/notify_test.go
Labels: T-Task

#3066 Remove `PerformError`
  clientapi/routing/admin.go
  clientapi/routing/createroom.go
  clientapi/routing/directory.go
  clientapi/routing/joinroom.go
  clientapi/routing/membership.go
  clientapi/routing/peekroom.go
  clientapi/routing/routing.go
  clientapi/routing/upgrade_room.go
  federationapi/routing/invite.go
  roomserver/api/api.go
  roomserver/api/perform.go
  roomserver/internal/api.go
  roomserver/internal/perform/perform_admin.go
  roomserver/internal/perform/perform_invite.go
  roomserver/internal/perform/perform_join.go
  roomserver/internal/perform/perform_peek.go
  roomserver/internal/perform/perform_publish.go
  roomserver/internal/perform/perform_unpeek.go
  roomserver/internal/perform/perform_upgrade.go
  roomserver/roomserver_test.go
  roomserver/storage/interface.go
  userapi/internal/user_api.go
Labels: T-Task

#3071 Add key backup tests
  clientapi/clientapi_test.go
  clientapi/jsonerror/jsonerror.go
  clientapi/routing/key_backup.go
  userapi/api/api.go
  userapi/internal/user_api.go
Labels: spec-compliance, T-Task
